name: Java CI with Maven
permissions:
  contents: read
  pages: write
  id-token: write
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Configure GitHub Pages
      uses: actions/configure-pages@v5
    - name: Create test config
      run: |
        mkdir -p src/test/resources
        cat > src/test/resources/config.properties <<'EOT'
        baseUrl=https://www.amazon.com/
        browser=chrome-headless
        timeout=10
        email=
        pass=
        existingProduct=HP VietNam
        nonExistingProduct=acdxyz3245
        EOT
    - name: Run Search tests with Maven
      run: mvn clean -Dtest=tests.Search.Search test
    - name: Generate Allure Report
      if: always()
      run: mvn allure:report
    - name: Upload Allure Report artifact
      if: always()
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./target/site/allure-maven-plugin
    - name: Deploy Allure Report to GitHub Pages
      if: always()
      id: deployment
      uses: actions/deploy-pages@v4
